### ISSUE TITLE
clean up mock endpoints

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#110]
- remove/mock part of API and associated resources
dependency: #109

**Comment by jusdino** [comment]
After we are fully migrated over to the /v1 api, we will need to remove:
- all `/mock` and `/v0` paths from the API, all associated lambdas
- The `mock_bucket: true` support from the `BulkUploadsBucket` construct
- the `license-data` lambda package
- the `delete-objects` lambda package
- the mock/deprecated data resources from the `PersistentStack`

Note that this may have to be done in two waves to work through cross-stack dependencies:
- api updates first to remove data resource dependencies from the API
- data resources second

**Comment by landonshumway-ia** [comment]
I have broken this ticket up into two parts, as it will require two changes that must be separately deployed all the way through the production environment to avoid issues with cross-stack dependencies. Part 1 of this effort is now in #338 

This ticket will be used to track part 2, which involves cleaning up the mock resources in the Persistent stack.

**Comment by landonshumway-ia** [comment]
Marking this ticket as currently blocked, until #338 has been deployed all of the way through production on the main branch.
