### ISSUE TITLE
evaulate payment processors

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#121]
evaluate the 2 potential payment processors (clover, authorize.net) for compatibility with the system. Are either preferred? Challenging to integrate? Not possible to use?
- document listing pros/cons, recommendation

**Comment by jlkravitz** [comment]
@isabeleliassen just out of curiosity, any reason we're not considering stripe?

**Comment by isabeleliassen** [comment]
@jlkravitz We're just considering processors that the Commissions already have experience with. We've had Stripe recommended before but no one was really interested.
