### ISSUE TITLE
backend API for CSG staff user management

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#147]
## User Story
As a superadmin, I want to be able to see all other access permissions so I can step in to resolve problems when necessary.

## Acceptance Criteria
- superadmins can see all data in the system (read and admin permissions)
- log user actions for traceability--is this possible?
- no need to directly impersonate other users
- no need to create new compacts
- ability to add/remove/disable other levels of users
- if an existing user who is disabled is re-invited, they will be re-enabled
- all invited users including re-invites should include email notification to create a password

Reference #125

**Comment by jusdino** [comment]
After discussion this morning, we decided to carve the user status information for the staff user's list view into a separate ticket:
#214
