### ISSUE TITLE
UI for admin profile page (design)

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#177]
## User Story
As an administrator, I want to be able to change my personal information on file so that I can keep the information current.

### Acceptance Criteria
- name, email address, and password (hidden) are listed on the page
- an edit button is available next to each of these
- the compact or compacts a person has access to are listed in their profile. If it is a state administrator, the state is also listed
- we may want to discuss security measures when changing an email or password

**Comment by isabeleliassen** [comment]
@becca-collins

**Comment by becca-collins** [comment]
@isabeleliassen @jsandoval81 @jusdino 

Here's a Figma design for the Admin Profile (I renamed it to Account) screen: https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/branch/OSig8ey2HeH7uXYyFI6901/JCC?m=auto&node-id=6673-1150&t=ezkUgThqAZXnUyu9-1

**Comment by becca-collins** [comment]
@jsandoval81 @jusdino The design above has been updated based on our feedback!

**Comment by isabeleliassen** [comment]
On the current profile page, the email is editable, but we need to change it to read only due to a recent discussion @becca-collins

**Comment by becca-collins** [comment]
@isabeleliassen This has been updated in the designs!
