### ISSUE TITLE
Email template design

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#179]
## User Story
As an administrator, I want to receive an email notifying me when I am invited to be a compact user so that I can log in and test the system

### Acceptance Criteria 
- header, footer?
- CompactConnect logo at top of message
- user invitation text:
Hello [name],
Welcome to CompactConnect. You have been added as a user for [state and/or compact]. You may log in with the credentials below. You will be asked to designate a new password and set up two-factor authentication before you can use the site.
Username: [email]
Temporary password:

### Notes
- This template will ideally be recycled for future email notifications, such as notifying a user that their data did not upload successfully, notifying users that their privileges will expire, or notifying users of new adverse actions.
- We will want to consider/preview what this message looks like if the inbox provider converts it to a plain text format.

**Comment by becca-collins** [comment]
@isabeleliassen @jusdino @jsandoval81 

Here is the email template design in Figma: https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6637-588&t=ZcLKs1Vo7T53pHTG-1
