### ISSUE TITLE
mobile designs for privilege purchase and licensee profile and licensee login

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#191]
- use existing desktop designs as references

**Comment by becca-collins** [comment]
@jsandoval81 Here are some responsive designs in Figma:

- [Licensee login](https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6812-1547&t=vbjUfgoBi5VGFJzG-1)
- [Licensee/Applicant dashboard](https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6812-1373&t=vbjUfgoBi5VGFJzG-1)
- [Applicant privilege purchasing flow](https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6678-2752&t=vbjUfgoBi5VGFJzG-1) (I'm still finishing the mobile designs for this one)

**Comment by becca-collins** [comment]
@isabeleliassen @jsandoval81 These are all complete now!
