### ISSUE TITLE
Read Permissions (backend)

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#207]
- state administrators can view all the data for those that have a license or privilege in their state (this includes a license that is not the "home state" license)
- state administrators can see public information for those that are in their state. This includes license and discipline, DOB, address, and phone/email (SSN the only item considered private and is addressed in a separate ticket)
- compact administrators can view all data for all their profession
- convert read permission from compact level to state level (maybe?)
- scoped down as read all in your state and read none outside of your state
- Realistic test data in preprod/csg test env to ensure limited read permissions functional

**Comment by jusdino** [comment]
Some questions for clarification:

For your second bullet, do you mean:
> state administrators can only see public information for those that are *not* in their state. This includes license and discipline. It may include DOB, address, and phone/email (research needed)

When we are talking about state or compact administrators, we really mean any state board or compact staff with read access for their jurisdiction or state, right? For sake of clarity, so far, admins for the system are individuals with permission to do user management activities, while other staff may have separate provider data read and/or write permissions and not be admins.

If I understand right so far, it sounds like, ultimately, what we are talking about is a change that can be boiled down as:
- All staff users can read all public data within their compact
- We need to add more fine-grained control to allow staff users to:
  - read private data for providers with a license/privilege in one jurisdiction; or
  - read private data for all providers in the compact.

If all that is good with you, I think this can all be controlled in the back-end with no API or UI changes needed.

**Comment by landonshumway-ia** [comment]
Capturing this here for future reference. The following changes will need to be made to the backend to support this:

1. Create Staff users endpoint updated to replace 'read' action with 'readPrivate' action in compact and jurisdiction scopes.
2. CDK persistent stack updated to replace 'read' course grained scope with 'readGeneral' course grained scope
3. Pre-token generator lambda function updated to automatically grant 'readGeneral' course grained scope to all staff users, also allow 'readPrivate' action in jurisdictions scopes. 
4. Update query/get provider endpoints to add the following rules:

- If a staff user queries/gets info outside of their compact privilege - return 403
- If a staff user queries outside of their jurisdiction privilege - only return general information
- If a staff user queries for a licensee, and any of that licensee's records are for a jurisdiction the staff user had permissions in, return private information for all records for that provider.
