### ISSUE TITLE
applicant dashboard show all licenses and privileges

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#229]
- home state us still indicated at the top of the dashboard
- each license or privilege is shown in its own box
- the following information is shown for each: whether it is a license or a privilege, state, issue date, expiration date, and discipline
- discipline item can read "discipline status: no discipline"

**Comment by isabeleliassen** [comment]
@becca-collins @ChiefStief Here is what I am picturing for the new applicant dashboard!

**Comment by becca-collins** [comment]
@isabeleliassen These designs have been updated here! https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6575-1010&t=TDfgGINAnUSrdamv-1

**Comment by becca-collins** [comment]
@ChiefStief These designs are ready to go! (from the changes in the meeting Tuesday morning)

https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6575-1010&t=TDfgGINAnUSrdamv-1
