### ISSUE TITLE
Design for new licensee registration page

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#230]
- a page exists with the following fields: given name, family name, email, social security number, DOB
- the licensee needs to be able to access this page from somewhere--maybe the login page should have a "register as a new user" option?
- licensees receive a success confirmation message which says "you have successfully created an account. Any emails we have on file for you will be notified."
- licensees are asked to create a password
- licensees are directed to the dashboard

**Comment by becca-collins** [comment]
@isabeleliassen Are "Given name" and "Family name" the same as first and last name? It might be confusing to use those terms, as both might be seen as the same vs a "Chosen name" or nickname.
