### ISSUE TITLE
Create Privilege Purchase Interface

### ISSUE THREAD

**Issue by landonshumway-ia** [csg-org/CompactConnect#262]
Questions:
Are there taxes associated with this purchase flow? Where should that tax information come from? (API??) 

This ticket involves building out the interface as defined in this screenshot

![Image](https://github.com/user-attachments/assets/50475c1d-3c1c-4090-a0e6-561d52d2b872)

**Comment by isabeleliassen** [comment]
@landonshumway-ia I can't believe I'm saying this but I think this might be the first time I've heard a question about taxes. I'll check with our legal counsel but let's assume none for now.
