### ISSUE TITLE
Compact Admins add authorize.net account info (design)

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#280]

**Comment by landonshumway-ia** [comment]
@becca-collins For context on this design. Compact admins need to be able to upload their authorize.net credentials so we can store it securely for credit card transactions. This could be a really simple page with just two labeled fields:

"API Login ID"

"Transaction Key" (This should be a password field)

**Comment by isabeleliassen** [comment]
- will return error if the credentials are invalid
- admins can enter new credentials which will override existing credentials

**Comment by becca-collins** [comment]
@isabeleliassen This design has been updated here: https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=7775-23940&t=XteFXj7EW01wNYJf-1
