### ISSUE TITLE
associate provider ID with payment transactions

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#287]
- currently authorize.net would only capture billing name
- we ultimately need to be able to generate a list of who (name) has gotten a privilege in a state within a certain time period such as a month
- would we want to know their home state?

**Comment by landonshumway-ia** [comment]
@isabeleliassen For this point 'we ultimately need to be able to generate a list of who (name) has gotten a privilege in a state within a certain time period such as a month' how quickly does this list need to be generated? Will this information be needed just for reporting or will it need to be generated within the web application as well? How is this information intended to be used?

**Comment by landonshumway-ia** [comment]
Capturing answer here for future reference: each transaction will need the provider id included for transaction report generation. The backend will need to get the provider id from the transaction, use it to look up the provider name from our DB, and then insert that into the report that is generated.

**Comment by landonshumway-ia** [comment]
As part of this, I will be writing up an overview of the features we intend to support for V1 reporting using the information stored in authorize.net
