### ISSUE TITLE
attestation design updates

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#291]
Privilege purchase updates
- add field where license number is shown (ideally where the expiration date is right now, and then move the expiration date right)
- add the following two attestations at the bottom of the page. Both boxes must be checked before the applicant can move to the next screen
1. I hereby attest and affirm that this is my personal and licensure information and that I am a resident of the state listed on this page. 
2. I hereby attest and affirm that I have reviewed the address information provided herein and that this is my current address. I further consent to accept process of service at this address and will notify my home state of any change of Home State address or email address. I understand that I am only eligible for a Compact Privilege if I am a practitioner in my Home State, as that is defined in the Compact. If I mislead the Compact Commission about my Home State, the appropriate board may take action against my Compact Privilege, which may result in the revocation of other Compact Privileges I may hold. I will also be prohibited from obtaining any other Compact Privileges for a period of at least two (2) years.

Attestation updates
- the attestion page will now have two or three attestations. The military affiliation attestation only needs to appear for those who have military status documents uploaded. (If this is complicated on the dev end, we can discuss including it for all applicants)
- Investigations: There will be two options here, but the applicant can only select one. (1) I hereby attest and affirm that I am *not* currently under investigation by any board, agency, department, association, certifying body, or other body OR (2)I hereby attest and affirm that *I am currently under investigation* by any board, agency, department, association, certifying body, or other body. I understand that if any investigation results in a disciplinary action, my Compact Privileges may be rescinded. 
- If the applicant says they are under investigation, we want the following question to appear with a blank text box for their answer: Please indicate what organization or body is conducting the investigation:
- Military affiliation: I hereby attest and affirm that my current military status documentation as uploaded to CompactConnect is accurate.

**Comment by becca-collins** [comment]
@isabeleliassen
In the privilege purchasing flow, I've updated the content on the [personal information screen](https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6575-1111&t=T0aWboF1FFWBIHwk-1) and the [attestations screen](https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6575-1405&t=T0aWboF1FFWBIHwk-1).
