### ISSUE TITLE
Complete privilege purchase flow mobile designs

### ISSUE THREAD

**Issue by StacyNGriffin** [csg-org/CompactConnect#292]

**Comment by ChiefStief** [comment]
@isabeleliassen There are now mobile centric designs for this flow. These designs will necessitate some changes to the UI but will be a good improvement over what we have now and should address the issue at the heart of Brad's feedback as well.

Just a heads up that this ticket and work exists.

**Comment by ChiefStief** [comment]
Also: address bug where state selection drop down does not populate in built app
