### ISSUE TITLE
Backend handles purchase of expired privileges

### ISSUE THREAD

**Issue by landonshumway-ia** [csg-org/CompactConnect#295]
Currently, the system does not allow a licensee to purchase a privilege for the same jurisdiction twice, even if that previously purchased privilege is expired. The backend needs to handle the following case scenarios:

- Licensee has no active license (return 400 invalid request)
- Licensee has active license and is purchasing privilege for an existing privilege (preserve previous expired privilege, add new privilege)

As part of this ticket, we need to design how we will store previous privilege records so that it is returned along with the latest privilege record.

**Comment by landonshumway-ia** [comment]
@isabeleliassen question on this: If a licensee is attempting to purchase a privilege for the same jurisdiction, but does not have an updated license since their last purchase, should we prevent the purchase? In this case the expiration date for the privilege will be the same, so the purchase will not provide any value to the licensee.

**Comment by isabeleliassen** [comment]
@landonshumway-ia yes, we want to prevent the purchase in that case
