### ISSUE TITLE
Existing privilege handling changes

### ISSUE THREAD

**Issue by ChiefStief** [csg-org/CompactConnect#297]
Double check logic for purchase privilege button to not allow privilege purchase button if no active license.
Gray out privilege purchase choice if existing privilege for that state has same expiration date as active license.
Also, adjust licensee dahsboard to only show most recent privilege and license for each state

Three bug fix additions to this ticket related to the Select Privilege screen: 
1) Clicking state privilege choice check box exactly does not trigger checked state
2) Jurisprudence modal confirmation can be worked around by using keyboard navigation because the "next" button is enabled while the modal is open
3) The jurisprudence validation was tied directly to the clicking of the state option so clicking the exout did not reset properly

**Comment by landonshumway-ia** [comment]
Questions related to this that we should probably answer:

1. How would a license expiration date be updated? In this system? Or by the state uploading new information?
2. How does a state remove/delete expired licenses? Do they do this? Do we need to account for a license being removed from the system by an admin?
3. @becca-collins (Design) What should we show in the event that the privilege for a jurisdiction is not expired, but the licensee wants to buy it anyway (ie they have a renewed license and they want to update their expiration on the privilege)?

**Comment by isabeleliassen** [comment]
@landonshumway-ia 
1. Exp dates will be updated when a state uploads information.
2. There is no need to delete expired licenses (in fact, it is preferable to have a record of of previous licenses)
3. 4. Yes, it would be ideal to have some way to view past privileges
