### ISSUE TITLE
military affiliation backend

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#327]

**Comment by landonshumway-ia** [comment]
Based on the UI designs. The following additions will need to be implemented in the Backend to support this feature:

- New S3 bucket created for storing military affiliation documents (keyspace designed for storing versioned records). 
- POST endpoint added to store initial military affiliation record in the DB with a status of 'initializing', generate an S3 pre-sign URL, which frontend client will use to upload the document
- PUT endpoint added to update the status of the military affiliation. This will be used when the user has completed uploading their document, or is ending their affiliation.
```
{
  "status": "active | inactive"
}
```

- update the GET provider endpoints to parse the military affiliations objects and return them in the provider details.
- update purchase endpoints to reference these objects to determine a provider's military status

I will keep these efforts combined into this one ticket, as the changes will all need to be released together.
