### ISSUE TITLE
Licensee detail view updates

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#360]
Due to a number of changes admins have requested, the designs for the  licensee detail view need to be updated.
###
- the licensee detail view can be changed to look like the applicant dashboard
- each license or privilege should have room for a license or privilege number
- an added section of "personal information" should be present at the top. This section will display licensee address, NPI, and (for some administrators) DOB and SSN
- Under this section is "documents" section where the current and past home state documents can be viewed
- SSN is displayed as the last four digits with a "click to reveal full number" option
- If it's smoother, the personal info, current privileges, and past privileges could all be drop downs

**Comment by becca-collins** [comment]
Updated collapsed and expanded views here: https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=8119-2603&t=wIjypeG9Vk1U1GXF-1
