### ISSUE TITLE
further redesign to attestations

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#378]
- due to recent discussions, a few changes need to be made to existing pages
- On the general attestations page, please add two attestations. One on discipline and one on provision of true information.
- Discipline attestation:
I hereby attest and affirm that I:
1) Have no encumbrance (any discipline that restricts my full practice or any unmet condition before returning to a full and unrestricted license, including, but not limited, to probation, supervision, completion of a program, and/or completion of CEs) on ANY state license;
2) Have not had any encumbrance on ANY state license within the previous two years from date of this application for a Compact Privilege.

- provision of true information: I hereby attest and affirm that all information contained in this privilege application is true to the best of my knowledge.

- under the investigations attestation, if someone says they're under investigation, we want them to have a write-in box appear, which will say "Please indicate what organization or body is conducting the investigation."

- please double check the language of current attestations against the file here
- [Attestations v4.docx](https://github.com/user-attachments/files/18098966/Attestations.v4.docx)

**Comment by becca-collins** [comment]
@isabeleliassen These designs have been updated here!
https://www.figma.com/design/SYM0uWszsu8Sf0YfxAhIMY/JCC?m=auto&node-id=6575-1405&t=oAdahesMoewGKElO-1
