### ISSUE TITLE
CSG AWS setup

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#82]
### Acceptance Criteria
- Set up CSG AWS account in accordance with PR
- IA verifies that deployments automatically succeed from GitHub activity in CSG's repo

**Comment by jusdino** [comment]
Waiting for AWS support RE limits preventing set up

**Comment by jusdino** [comment]
I've got all the AWS Accounts and basic security controls in place at this point. I just need assistance from someone in CSG with administrative permissions in the CSG GitHub Organization who can help me set up pipeline integration to complete this ticket.
