### ISSUE TITLE
Data Access and Modeling

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#84]
## User Story
As a staff member, I want to be able to look up licensees so that I can know what licenses and privileges they have.

### Acceptance Criteria
- Adjust access model based on user research/how users access data
- Incorporates user research from compact admins
- Accommodates desire to represent individuals, not just licenses/privileges (currently queries are set up for licenses/privileges)
- Supports resolving conflicted data from different states
- Gracefully handles race conditions of different states uploading conflicting data for a new/existing licensee at the same time
- Does not preclude future addition of filtering by licensee attributes (keeping our options open)
- Prevents compact/board admins from accessing non-public data for other compacts
- Accommodates military status with residence not matching home license state

### Discussion items 
Complete #87

**Comment by jusdino** [comment]
AC should include:
- Incorporates user research from compact admins
- Accommodates desire to represent individuals, not just licenses/privileges
- Supports some level of resolving conflicted data from different states
- Gracefully handles race conditions of different states uploading conflicting data for a new/existing user at the same time
