### ISSUE TITLE
instrumentation for monitoring and alerting

### ISSUE THREAD

**Issue by isabeleliassen** [csg-org/CompactConnect#94]
## User Story
As a staff member, I want to know when errors occur so that I can make sure to address problems with the system.

### Acceptance Criteria
- Operational staff receive alert for expected error conditions via slack
- separate slack channel set up to receive these
- Alert communications should be sent when:

    The API returns a 5XX status for any reason
    More than 50% of requests result in a 4XX response
    A lambda gets throttled
    The max message age of the ingest queue reaches more than half its retention period
    The ingest DLQ has unusually high activity (threshold TBD)
    Code deploys have started/completed/failed

Note: setting up slack notifications will involve manual authorization process

**Comment by jusdino** [comment]
Acceptance Criteria:
Alert communications should be sent when:
- The API returns a 5XX status for any reason
- More than 50% of requests result in a 4XX response
- A lambda gets throttled
- The max message age of the ingest queue reaches more than half its retention period
- The ingest DLQ has unusually high activity (threshold TBD)
